- name: Crear directorio .kube
  file:
    path: $HOME/.kube
    state: directory

# Es necesario cambiar los permisos antes de copiar el fichero
# añadiendo permisos de lectura para otros
- name: Permisos de lectura para el fichero
  file:
    path: /etc/kubernetes/admin.conf
    mode: o+r

- name: Copy file with owner and permissions
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config