apiVersion: v1
kind: Namespace
metadata:
  name: game
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
  namespace: game
  labels:
    app: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
      containers:
      - name: game
        image: quay.io/rhte_2019/2048-game:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/datos_nfs"
            name: nfs 
        readinessProbe:
          httpGet:
            path: /
            port: 80 
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
    name: game-service
    namespace: game
spec:
    selector:
      app: game
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game
  namespace: game
  labels:
    app: game
  # A침adida la anotaci칩n para que se sirvan correctamente los est치ticos
  annotations:
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  rules:
  # Sustituir el host con el nombre que se desee
  - host: http://kubendikamaster.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: "Prefix"
        backend:
          service:
            name: game-service
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-configmap
  namespace: game
data:
  servers-increment: "42"
  ssl-redirect: "OFF"
---
# Aunque no se utilice se a침ade un volumen al contenedor
# para comprobar que el nfs funciona correctamentes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: master.azure
    path: "/srv/nfs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  namespace: game
  labels:
    app: game
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
