# Configuración que se realiza en todos los servidores
# directorio roles/comunes/tasks
# - instalar rpm
# - arrancar servicios servicios
# - configurar la zona horaria
# - desactivación de selinux
# - añadir nombres de máquinas en el etc/hosts
# - añadir características firewall
# - desactivación de swap
- name: Configuracion inicial
  hosts: all
  become: true
  vars_files:
    - "all_vars/common.yaml"
  gather_facts: false
  roles:
    - comunes