# Configuración para el uso de docker y kubernetes
# directorio roles/containers/tasks
# - instalar docker
# - instalar kubernetes
- name: Configuracion contenedores
  hosts: all
  become: yes
  vars_files:
    - "all_vars/container.yaml"
  gather_facts: false
  roles:
    - containers