# Configuración del kubernetes en el nodo master
# directorio roles/k8smaster/tasks
# - configurar reglas de firewall
# - ejecutar kubeadm init
# - copiar la configuración de kubernetes a la home de root
- name: Configuracion master
  hosts: master
  become: yes
  vars_files:
    - "all_vars/k8smaster.yaml"
    - "all_vars/common.yaml"
  gather_facts: false
  roles:
    - k8smaster