# Configuración de cilium como SDN desde el nodo master
# directorio roles/cilium/tasks
# - instalación de cilium y configuración del cidr
- name: Instalacion calico
  hosts: master
  become: yes
  vars_files:
    - "all_vars/k8smaster.yaml"
  gather_facts: false
  roles:
    - cilium