# Instalación de Ingress para el enrutamiento de peticiones con nombres de host
# directorio roles/ingress/tasks
# - instalación de ingress
- name: Instalacion de Ingress
  hosts: master
  become: yes
  vars_files:
    - "all_vars/common.yaml"
    - "all_vars/ingress.yaml"
  gather_facts: false
  roles:
    - ingress